name: Build

on:
  release:
    types: [published]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    name: Docker build

    steps:
      - uses: actions/checkout@v2

      - name: Build Azure Billing Exporter docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pritchinpavel/azure_billing_exporter
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
